"use strict";
/**
 * Every TCP message pattern the gateway can send, and every pattern a service
 * listens for, declared in one place. Gateway and service import the same
 * constant, so a renamed pattern is a compile error rather than a request that
 * silently times out.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NOTIFICATION_PATTERNS = exports.EVENTS_PATTERNS = exports.ATLAS_PATTERNS = exports.GALLERY_PATTERNS = exports.CONTENT_PATTERNS = exports.REGISTRATION_PATTERNS = exports.USER_PATTERNS = exports.AUTH_PATTERNS = exports.SERVICE_TOKENS = void 0;
exports.SERVICE_TOKENS = {
    AUTH: 'AUTH_SERVICE',
    USER: 'USER_SERVICE',
    REGISTRATION: 'REGISTRATION_SERVICE',
    CONTENT: 'CONTENT_SERVICE',
    GALLERY: 'GALLERY_SERVICE',
    ATLAS: 'ATLAS_SERVICE',
    EVENTS: 'EVENTS_SERVICE',
    NOTIFICATION: 'NOTIFICATION_SERVICE',
};
exports.AUTH_PATTERNS = {
    LOGIN: 'auth.login',
    REGISTER: 'auth.register',
    LOGOUT: 'auth.logout',
    REFRESH: 'auth.refresh',
    ME: 'auth.me',
    CHANGE_PASSWORD: 'auth.change_password',
    FORGOT_PASSWORD: 'auth.forgot_password',
    RESET_PASSWORD: 'auth.reset_password',
    VALIDATE_TOKEN: 'auth.validate_token',
};
exports.USER_PATTERNS = {
    FIND_ALL: 'user.find_all',
    FIND_ONE: 'user.find_one',
    CREATE: 'user.create',
    UPDATE: 'user.update',
    REMOVE: 'user.remove',
    BULK_REMOVE: 'user.bulk_remove',
    BULK_STATUS: 'user.bulk_status',
    RESET_PASSWORD: 'user.reset_password',
    ASSIGN_ROLES: 'user.assign_roles',
    STATS: 'user.stats',
    ROLE_FIND_ALL: 'role.find_all',
    ROLE_FIND_ONE: 'role.find_one',
    ROLE_CREATE: 'role.create',
    ROLE_UPDATE: 'role.update',
    ROLE_REMOVE: 'role.remove',
    ROLE_RESTORE: 'role.restore',
    ROLE_TOGGLE_STATUS: 'role.toggle_status',
    ROLE_STATS: 'role.stats',
    ROLE_SYNC_PERMISSIONS: 'role.sync_permissions',
    ROLE_MATRIX: 'role.matrix',
    PERMISSION_FIND_ALL: 'permission.find_all',
    PERMISSION_FIND_ONE: 'permission.find_one',
    PERMISSION_CREATE: 'permission.create',
    PERMISSION_UPDATE: 'permission.update',
    PERMISSION_REMOVE: 'permission.remove',
    PERMISSION_RESTORE: 'permission.restore',
    PERMISSION_TOGGLE_STATUS: 'permission.toggle_status',
    PERMISSION_STATS: 'permission.stats',
    PERMISSION_MODULES: 'permission.modules',
    DEPARTMENT_FIND_ALL: 'department.find_all',
    DEPARTMENT_CREATE: 'department.create',
    DEPARTMENT_UPDATE: 'department.update',
    DEPARTMENT_REMOVE: 'department.remove',
    AUDIT_FIND_ALL: 'audit.find_all',
    AUDIT_RECORD: 'audit.record',
};
exports.REGISTRATION_PATTERNS = {
    DIASPORA_SUBMIT: 'diaspora.submit',
    DIASPORA_FIND_ALL: 'diaspora.find_all',
    DIASPORA_FIND_ONE: 'diaspora.find_one',
    DIASPORA_VERIFY: 'diaspora.verify',
    DIASPORA_REJECT: 'diaspora.reject',
    DIASPORA_STATS: 'diaspora.stats',
    COMMITTEE_SUBMIT: 'committee.submit',
    COMMITTEE_FIND_ALL: 'committee.find_all',
    COMMITTEE_FIND_ONE: 'committee.find_one',
    COMMITTEE_UPDATE: 'committee.update',
    COMMITTEE_CHANGE_STATUS: 'committee.change_status',
    COMMITTEE_REMOVE: 'committee.remove',
    COMMITTEE_CREATE_PORTAL_ACCOUNT: 'committee.create_portal_account',
    COMMITTEE_GENERATE_LOCAL_PASSWORD: 'committee.generate_local_password',
    COMMITTEE_STATS: 'committee.stats',
};
exports.CONTENT_PATTERNS = {
    ARTICLE_FIND_ALL: 'article.find_all',
    ARTICLE_FIND_ONE: 'article.find_one',
    ARTICLE_FIND_BY_SLUG: 'article.find_by_slug',
    ARTICLE_CREATE: 'article.create',
    ARTICLE_UPDATE: 'article.update',
    ARTICLE_REMOVE: 'article.remove',
    ARTICLE_WORKFLOW: 'article.workflow',
    ARTICLE_PUBLIC_LIST: 'article.public_list',
    ARTICLE_STATS: 'article.stats',
    CATEGORY_FIND_ALL: 'category.find_all',
    CATEGORY_FIND_ONE: 'category.find_one',
    CATEGORY_CREATE: 'category.create',
    CATEGORY_UPDATE: 'category.update',
    CATEGORY_REMOVE: 'category.remove',
    SUBCATEGORY_FIND_ALL: 'subcategory.find_all',
    SUBCATEGORY_FIND_ONE: 'subcategory.find_one',
    SUBCATEGORY_CREATE: 'subcategory.create',
    SUBCATEGORY_UPDATE: 'subcategory.update',
    SUBCATEGORY_REMOVE: 'subcategory.remove',
    MEDIA_FIND_ALL: 'content_media.find_all',
    MEDIA_CREATE: 'content_media.create',
    MEDIA_REMOVE: 'content_media.remove',
    PODCAST_FIND_ALL: 'podcast.find_all',
    PODCAST_FIND_ONE: 'podcast.find_one',
    PODCAST_FIND_BY_SLUG: 'podcast.find_by_slug',
    PODCAST_CREATE: 'podcast.create',
    PODCAST_UPDATE: 'podcast.update',
    PODCAST_REMOVE: 'podcast.remove',
    PODCAST_TOGGLE_STATUS: 'podcast.toggle_status',
    PODCAST_PUBLIC_LIST: 'podcast.public_list',
    PODCAST_FEATURED: 'podcast.featured',
    PODCAST_PLAY: 'podcast.play',
    PODCAST_REACT: 'podcast.react',
    PODCAST_SUBSCRIBE: 'podcast.subscribe',
    PODCAST_STATS: 'podcast.stats',
    PODCAST_RSS: 'podcast.rss',
};
exports.GALLERY_PATTERNS = {
    MEDIA_PUBLIC_LIST: 'gallery.public_list',
    MEDIA_FIND_ALL: 'gallery.find_all',
    MEDIA_FIND_ONE: 'gallery.find_one',
    MEDIA_MY_UPLOADS: 'gallery.my_uploads',
    MEDIA_CREATE: 'gallery.create',
    MEDIA_UPDATE: 'gallery.update',
    MEDIA_REMOVE: 'gallery.remove',
    MEDIA_MODERATION_QUEUE: 'gallery.moderation_queue',
    MEDIA_MODERATE: 'gallery.moderate',
    MEDIA_PUBLIC_FILTER_OPTIONS: 'gallery.public_filter_options',
    ALBUM_FIND_ALL: 'album.find_all',
    ALBUM_FIND_ONE: 'album.find_one',
    ALBUM_CREATE: 'album.create',
    ALBUM_UPDATE: 'album.update',
    ALBUM_REMOVE: 'album.remove',
    ALBUM_SYNC_MEDIA: 'album.sync_media',
    ALBUM_MEDIA_PICKER: 'album.media_picker',
};
exports.ATLAS_PATTERNS = {
    FIND_ALL: 'atlas.find_all',
    FIND_ONE: 'atlas.find_one',
    CREATE: 'atlas.create',
    UPDATE: 'atlas.update',
    REMOVE: 'atlas.remove',
    SUBMIT: 'atlas.submit',
    MODERATE: 'atlas.moderate',
    PUBLIC_LIST: 'atlas.public_list',
    MAP_DATA: 'atlas.map_data',
    STATS: 'atlas.stats',
    FORM_OPTIONS: 'atlas.form_options',
};
exports.EVENTS_PATTERNS = {
    WEBINAR_FIND_ALL: 'webinar.find_all',
    WEBINAR_FIND_ONE: 'webinar.find_one',
    WEBINAR_FIND_BY_SLUG: 'webinar.find_by_slug',
    WEBINAR_CREATE: 'webinar.create',
    WEBINAR_UPDATE: 'webinar.update',
    WEBINAR_REMOVE: 'webinar.remove',
    WEBINAR_TOGGLE_STATUS: 'webinar.toggle_status',
    WEBINAR_PUBLIC_LIST: 'webinar.public_list',
    WEBINAR_REPLAYS: 'webinar.replays',
    RSVP_CREATE: 'rsvp.create',
    RSVP_FIND_ALL: 'rsvp.find_all',
    RSVP_UPDATE_STATUS: 'rsvp.update_status',
    PUSH_SUBSCRIBE: 'push.subscribe',
};
exports.NOTIFICATION_PATTERNS = {
    SEND_EMAIL: 'notification.send_email',
    SEND_PUSH: 'notification.send_push',
    FIND_ALL: 'notification.find_all',
};
